[package]
name = "parrots"
version = "0.0.1"
edition = "2021"
description = "ParrotLib for Rust"
license = "GPL3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
